### ISSUE TITLE
ERR_INVALID_CALLBACK Upon Starting App

### ISSUE THREAD

**Issue by ChrisHuffman** [scripting/river5#30]
Upon starting the app, I will see several feed items being loaded through the console, but before I can even check it out on localhost, the app stops and I get the following error:

fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1159:14)
    at eval (eval at runUserScript (C:\Users\Nitro Dubz\Desktop\Web Dev\bootcamp\cryptonews\node_modules\river5\node_modules\davereader\davereader.js:2104:6), <anonymous>:8:5)
    at doLevel (C:\Users\Nitro Dubz\Desktop\Web Dev\bootcamp\cryptonews\node_modules\river5\node_modules\davereader\davereader.js:1907:7)
    at C:\Users\Nitro Dubz\Desktop\Web Dev\bootcamp\cryptonews\node_modules\river5\node_modules\davereader\davereader.js:1896:8
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)

**Comment by scripting** [comment]
@ChrisHuffman --

I just downloaded the current version of River5 and it runs here with the latest version of Node downloaded following the instructions on this page.

https://github.com/nodesource/distributions#debinstall

You must be running a later version that no longer supports a feature that River5 is using.

I am running Node v11.6.0.

You can tell what version you're running with this command.

node --version

Dave
