### ISSUE TITLE
Windows Install no worky out of the box.

### ISSUE THREAD

**Issue by ssantoni** [scripting/river5#32]
Downloaded the code, installed Node, node river5.js gives this error (pasted below)...
I have an older version of River which works fine and seems to have a lot more folders/structure to the code than this latest version here.  Also the older river5.js points to 
var feedtools = require ("./lib/feedtools.js");

The new version points to the davereader module, but it's not present in the downloaded code.
Is this code just meant to be an update to existing versions?

C:\river5>node river5.js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'davereader'
Require stack:
- C:\river5\river5.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:745:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\river5\river5.js:24:17)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:937:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\river5\\river5.js'←[39m ]

**Comment by ssantoni** [comment]
Forgot to run npm update which brings in the davereader tools... that resolved it...
